"""baseline

Revision ID: 1956e03a1fef
Revises: 42ab167c2a0a
Create Date: 2025-01-08 11:43:50.963190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1956e03a1fef'
down_revision: Union[str, None] = '42ab167c2a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dob')
    op.drop_table('phones')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('seeds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seed', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dob_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dob_id'], ['dob.id'], name='seeds_dob_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='seeds_location_id_fkey'),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], name='seeds_phone_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='seeds_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='seeds_pkey')
    )
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('street_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('street_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='locations_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_table('phones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='phones_pkey')
    )
    op.create_table('dob',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dob_pkey')
    )
    # ### end Alembic commands ###
